### ISSUE TITLE
500 error, no logs

### ISSUE THREAD

**Issue by prologic** [ordinary-dev/phoenix#81]
Hey! 👋

I'm not very familiar with Gin, and don't normally use any web frameworks myself in my projects. Since some ~8hr ago, my phoenix instance started reporting 500 errors for every request. I'm not able to bring it back online in any way. I checked the database with `sqlite` and it appears to be fine. Near as I can tell there are also no logs either. Is this failing deep within Gin somewhere? How? Why all of a sudden? How does one even debug this?!

**Comment by prologic** [comment]
No amount of restart, or rebuild or redeployment has worked so far. It's really weird.

**Comment by ordinary-dev** [comment]
Thanks for the bug report, I'll add more logs. The project is unpolished in many aspects, but I use it myself and have not noticed such problems.

Judging by the fact that a 500 error is at least returned, the server starts successfully. I'll check the request handlers.

**Comment by prologic** [comment]
Hey! Thanks for replying! This sadly (_shame on me_) was a red herring on my part. I'll share what happened though, as it was this Phoenix instance where I first discovered this.

After hours of debugging, I eventually landed on a random Traefik issue https://github.com/traefik/traefik/issues/3163 that happened to mention turning up the logging level to `DEBUG`. I did that and discovered the following error(s) that were only visible in debug logs :/

```
2024-03-23T05:35:42Z" level=debug msg="Error calling http://authelia:9091/api/verify?rd=https://auth.mydomain.tld. Cause: Get \"http://authelia:9091/api/verify?rd=https://auth.mydomain.tld\": dial tcp: lookup authelia on 127.0.0.11:53: no such host" middlewareName=authelia@docker middlewareType=ForwardedAuthType
```

I have a few service (such as Phoenix) behind Authelia's Proxy auth and using Traefik's Docker-based middleware. Unfortunately the middleware has disappeared "somehow" despite the service still running just fine. This was resulting in `500` erro(s) with zero content, requests were not reaching any backend with this middleware configured.

So adding additional logging won't really help in this cse, but I did notice that we don't really log errors. So my fork addes some additional calls to `logrus.WithError(err).Error()` in a few places.
